### ISSUE TITLE
TSF vs TSC

### ISSUE THREAD

**Issue by rdyan0053** [ddz16/TSFpaper#1]
excuse me, I am a newbie in this field. I want to ask what is the difference between Time Series Forecasting (TSF) and Time Series Classification(TSF, i.e. the ecg classification and eeg classification)?
Could you recommend some papers on time series classification (TSC)?
Thank you!

**Comment by ddz16** [comment]
TSC and TSF are two completely different tasks, but they also have similarities. 

The difference lies in the definition of the tasks. The purpose of TSC is to classify time series, such as an electrocardiogram time series, which may be caused by a certain type of disease. Therefore, the TSC task is to identify which type of disease the electrocardiogram time series belongs to. However, the purpose of TSF is to predict the future time series based on past, such as if you know the electrocardiogram time series of a person in the past few hours, you hope to predict the value of the electrocardiogram in the future. 

The similarity is that the focus of both tasks is how to design a model that models the temporal relationship to better extract features of time series in the context of deep learning. Therefore, the backbone of the TSF method can also be used for TSC. For example, the [TimesNet](https://openreview.net/pdf?id=ju_Uqw384Oq) paper mentioned in this paper list.

Here is a [review](https://arxiv.org/abs/2304.13029) on TSC, where you can find some related papers. You can also find some TSC papers in this [Repo](https://github.com/qingsongedu/awesome-AI-tutorials-surveys).

**Comment by rdyan0053** [comment]
Thanks again

**Comment by rdyan0053** [comment]
> TSC and TSF are two completely different tasks, but they also have similarities. 
> 
> The difference lies in the definition of the tasks. The purpose of TSC is to classify time series, such as an electrocardiogram time series, which may be caused by a certain type of disease. Therefore, the TSC task is to identify which type of disease the electrocardiogram time series belongs to. However, the purpose of TSF is to predict the future time series based on past, such as if you know the electrocardiogram time series of a person in the past few hours, you hope to predict the value of the electrocardiogram in the future. 
> 
> The similarity is that the focus of both tasks is how to design a model that models the temporal relationship to better extract features of time series in the context of deep learning. Therefore, the backbone of the TSF method can also be used for TSC. For example, the [TimesNet](https://openreview.net/pdf?id=ju_Uqw384Oq) paper mentioned in this paper list.
> 
> Here is a [review](https://arxiv.org/abs/2304.13029) on TSC, where you can find some related papers. You can also find some TSC papers in this [Repo](https://github.com/qingsongedu/awesome-AI-tutorials-surveys).

Thanks so much!
