### ISSUE TITLE
Recommendation: A necessary talk at NeurIPS to check before doing research in TSF

### ISSUE THREAD

**Issue by JingzheShi** [ddz16/TSFpaper#41]
Hi @ddz16,
Thank you so much for making this great repository about TSF papers!

I am Jingzhe Shi, the author of [Scaling Law for Time Series Forecasting](https://arxiv.org/abs/2405.15124) [NeurIPS 24'], which is included in this repo. (thanks a lot for the credit!)

However, **the more paper I read in this field, the more I have been enveloped in a weird feeling that there have been something wrong and inconsistent with this whole field**. Are benchmarks fair? Are current methods good? Are they making progress? Are they truly better than simple methods or old methods? Of-course many are better than linear regression and DLinear, but what if we look into history and find some simple, old but widely-used method from 50 years ago that can beat our NN-based methods?

Recently I saw a talk at NeurIPS 24' by Christoph Bergmeir: https://cbergmeir.com/talks/neurips2024/, in which these very important problems are discussed, from a very rigorous perspective. **It is very fortunate to have such a talk to tear the scab right off the sore, to reveal that there have been something wrong with our benchmarks and our methods in the time series forecasting community**. This talk makes me understand why I have been feeling so weird. It is as inspiring as the DLinear paper yet showing no mercy.

Therefore, **I think it would be good for every time series researcher to check this talk before doing researches, or reading more papers**. **I suggest put the link to this talk (or related papers) in a special position in this repository that anyone who see this repository can see and check, before they read more papers in the field**.

I fully understand that this is more a repo about papers rather than links to talks, and please disgard this issue if it is better not to include talks, or there have been enough papers about related topics.

Thank you!

Jingzhe Shi

**Comment by ddz16** [comment]
I have watched this talk and give some comments in my own blog (https://zhuanlan.zhihu.com/p/15567050440). I will add the link to the talk in my repository. Thank you for your reminder.

Dazhao Du
&nbsp;


杜大钊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月29日(星期天) 晚上11:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [ddz16/TSFpaper] Recommendation: A necessary talk at NeurIPS to check before doing research on TSF (Issue #41)














 
Hi @ddz16,
 Thank you so much for making this great repository about TSF papers!
 
I am Jingzhe Shi, the author of Scaling Law for Time Series Forecasting [NeurIPS 24'], which is included in this repo. (thanks a lot for the credit!)
 
However, the more paper I read in this field, the more I have been enveloped in a weird feeling that there have been something wrong and inconsistent with this whole field. Are benchmarks fair? Are current methods good? Are they making progress? Are they truly better than simple methods or old methods? Of-course many are better than linear regression and DLinear, but what if we look into history and find some simple, old but widely-used method from 50 years ago that can beat our NN-based methods?
 
Recently I saw a talk at NeurIPS 24' by Christoph Bergmeir: https://cbergmeir.com/talks/neurips2024/, in which these very important problems are discussed, from a very rigorous perspective. It is very fortunate to have such a talk to tear the scab right off the sore, to reveal that there have been something wrong with our benchmarks and our methods in the time series forecasting community. This talk makes me understand why I have been feeling so weird. It is as inspiring as the DLinear paper yet showing no mercy.
 
Therefore, I think it would be good for every time series researcher to check this talk before doing researches, or reading more papers. I suggest put the link to this talk (or related papers) in a special position in this repository that anyone who see this repository can see and check, before they read more papers in the field.
 
I fully understand that this is more a repo about papers rather than links to talks, and please disgard this issue if it is better not to include talks, or there have been enough papers about related topics.
 
Thank you!
 
Jingzhe Shi
